{% set name = "python-ldap" %}
{% set version = "3.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab26c519a0ef2a443a2a10391fa3c5cb52d7871323399db949ebfaa9f25ee2a0

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - setuptools
    - python
    - pyasn1
    - pyasn1-modules
    - openldap >=2.4.11
  run:
    - python
    - pyasn1
    - pyasn1-modules
    - openldap >=2.4.11

test:
  imports:
    - ldap
    - ldap.controls
    - ldap.extop
    - ldap.schema

about:
  home: https://www.python-ldap.org/
  license: PSF-2.0 and MIT
  license_file:
    - LICENCE
    - LICENCE.MIT
  summary: Python modules for implementing LDAP clients
  doc_url: https://www.python-ldap.org/en/latest/
  dev_url: https://github.com/python-ldap/python-ldap

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xylar
