appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jBTGiuXdNEBW7wxvC8gs/ucpmyVZ3x+wUoiwgoCPD5Ya+J8I9EE6Mc9/LNki+CKedg+v+mrdtrUOexRTuJcSxiy8iVNkfgd0opiLwIrYh9oFuRwsIVXzlsI/thfjVPPv0Vn4s0bv9yzemY3BXmsp9GtN+ZGr2RflJrMAd3kwQxRiHF717NdJ0bPF/EXzpa5+iQ4BgajYHTJCd61uiSLM5WIWBAk4M0LbZtC3PkxnjPs2Ohuyz2oD+sLI2woXVgArNfk8GKw2SPdnjfuxotJFKjDzN851Ho6B4YrB6mL/GofedS7CcvjXdh1hrwGyyJpHflqKRFBwU3p10uSXnx+iBOGRN50VhA77opgQaQtc2PBAW6CO/LX0Jy8ftG6CfJfOjFxdRYeTpBwq4SysOm42JxHUdkVPvhxxja/NBhcVgJZ2FEIlqdyYXEZSGlzups8rknfJ9R4xy0nsBMrqIQQkAav16mGmWHYnrw4HYH/mhuv1Jp2vD7L0F9vBLdixXWpNrivnGP/465qAxM7aKP+CEzoyYqNjr/bR1NW0SwpS7rirJPVtbnub4OELGKIaMMVLfm0GwL8ejBp0xfhaPWPHQi/xl28klvqg7h3n4K79UwzavPXIUvA5cpUK3TeZR4+buAJNDul4yx9PPWm2hMxOY9H3PCfZzjsB6FHA/eIl0FM=}
